/************************************************************************************************************************
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
************************************************************************************************************************/

--1
DECLARE @final INT = 0, @previous INT = 1, @current INT = 2 
WHILE @current < 4000000
BEGIN
    SELECT 
        @final += CASE WHEN @current%2 = 0 THEN @current ELSE 0 END,
        @current += @previous,
        @previous = @current - @previous
END
SELECT @final AS val1
